export interface BatangasCityAddress {
  id: string;
  barangay: string;
  city: string;
  province: string;
  fullAddress: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
}

export const batangasCityBarangays: BatangasCityAddress[] = [
  // Urban Barangays (Poblacion)
  {
    id: "bg001",
    barangay: "Barangay 1 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 1 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7565, lng: 121.0584 },
  },
  {
    id: "bg002",
    barangay: "Barangay 2 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 2 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7572, lng: 121.0591 },
  },
  {
    id: "bg003",
    barangay: "Barangay 3 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 3 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7578, lng: 121.0598 },
  },
  {
    id: "bg004",
    barangay: "Barangay 4 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 4 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7585, lng: 121.0605 },
  },
  {
    id: "bg005",
    barangay: "Barangay 5 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 5 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7592, lng: 121.0612 },
  },
  {
    id: "bg006",
    barangay: "Barangay 6 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 6 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7599, lng: 121.0619 },
  },
  {
    id: "bg007",
    barangay: "Barangay 7 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 7 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7606, lng: 121.0626 },
  },
  {
    id: "bg008",
    barangay: "Barangay 8 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 8 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7613, lng: 121.0633 },
  },
  {
    id: "bg009",
    barangay: "Barangay 9 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 9 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.762, lng: 121.064 },
  },
  {
    id: "bg010",
    barangay: "Barangay 10 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 10 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7627, lng: 121.0647 },
  },
  {
    id: "bg011",
    barangay: "Barangay 11 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 11 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7634, lng: 121.0654 },
  },
  {
    id: "bg012",
    barangay: "Barangay 12 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 12 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7641, lng: 121.0661 },
  },
  {
    id: "bg013",
    barangay: "Barangay 13 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 13 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7648, lng: 121.0668 },
  },
  {
    id: "bg014",
    barangay: "Barangay 14 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 14 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7655, lng: 121.0675 },
  },
  {
    id: "bg015",
    barangay: "Barangay 15 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 15 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7662, lng: 121.0682 },
  },
  {
    id: "bg016",
    barangay: "Barangay 16 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 16 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7669, lng: 121.0689 },
  },
  {
    id: "bg017",
    barangay: "Barangay 17 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 17 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7676, lng: 121.0696 },
  },
  {
    id: "bg018",
    barangay: "Barangay 18 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 18 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7683, lng: 121.0703 },
  },
  {
    id: "bg019",
    barangay: "Barangay 19 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 19 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.769, lng: 121.071 },
  },
  {
    id: "bg020",
    barangay: "Barangay 20 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 20 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7697, lng: 121.0717 },
  },
  {
    id: "bg021",
    barangay: "Barangay 21 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 21 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7704, lng: 121.0724 },
  },
  {
    id: "bg022",
    barangay: "Barangay 22 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 22 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7711, lng: 121.0731 },
  },
  {
    id: "bg023",
    barangay: "Barangay 23 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 23 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7718, lng: 121.0738 },
  },
  {
    id: "bg024",
    barangay: "Barangay 24 (Poblacion)",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Barangay 24 (Poblacion), Batangas City, Batangas",
    coordinates: { lat: 13.7725, lng: 121.0745 },
  },

  // Rural Barangays
  {
    id: "bg025",
    barangay: "Balagtas",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Balagtas, Batangas City, Batangas",
    coordinates: { lat: 13.7832, lng: 121.0952 },
  },
  {
    id: "bg026",
    barangay: "Balete",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Balete, Batangas City, Batangas",
    coordinates: { lat: 13.7945, lng: 121.1065 },
  },
  {
    id: "bg027",
    barangay: "Banaba Center",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Banaba Center, Batangas City, Batangas",
    coordinates: { lat: 13.8058, lng: 121.1178 },
  },
  {
    id: "bg028",
    barangay: "Banaba Ibaba",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Banaba Ibaba, Batangas City, Batangas",
    coordinates: { lat: 13.8171, lng: 121.1291 },
  },
  {
    id: "bg029",
    barangay: "Banaba Kanluran",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Banaba Kanluran, Batangas City, Batangas",
    coordinates: { lat: 13.8284, lng: 121.1404 },
  },
  {
    id: "bg030",
    barangay: "Banaba Silangan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Banaba Silangan, Batangas City, Batangas",
    coordinates: { lat: 13.8397, lng: 121.1517 },
  },
  {
    id: "bg031",
    barangay: "Bilogo",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Bilogo, Batangas City, Batangas",
    coordinates: { lat: 13.7432, lng: 121.0345 },
  },
  {
    id: "bg032",
    barangay: "Bolbok",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Bolbok, Batangas City, Batangas",
    coordinates: { lat: 13.7545, lng: 121.0458 },
  },
  {
    id: "bg033",
    barangay: "Bukal",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Bukal, Batangas City, Batangas",
    coordinates: { lat: 13.7658, lng: 121.0571 },
  },
  {
    id: "bg034",
    barangay: "Calicanto",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Calicanto, Batangas City, Batangas",
    coordinates: { lat: 13.7771, lng: 121.0684 },
  },
  {
    id: "bg035",
    barangay: "Catandala",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Catandala, Batangas City, Batangas",
    coordinates: { lat: 13.7884, lng: 121.0797 },
  },
  {
    id: "bg036",
    barangay: "Concepcion",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Concepcion, Batangas City, Batangas",
    coordinates: { lat: 13.7997, lng: 121.091 },
  },
  {
    id: "bg037",
    barangay: "Conde Itaas",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Conde Itaas, Batangas City, Batangas",
    coordinates: { lat: 13.811, lng: 121.1023 },
  },
  {
    id: "bg038",
    barangay: "Conde Labak",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Conde Labak, Batangas City, Batangas",
    coordinates: { lat: 13.8223, lng: 121.1136 },
  },
  {
    id: "bg039",
    barangay: "Cuta",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Cuta, Batangas City, Batangas",
    coordinates: { lat: 13.8336, lng: 121.1249 },
  },
  {
    id: "bg040",
    barangay: "Dalig",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Dalig, Batangas City, Batangas",
    coordinates: { lat: 13.8449, lng: 121.1362 },
  },
  {
    id: "bg041",
    barangay: "Dela Paz",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Dela Paz, Batangas City, Batangas",
    coordinates: { lat: 13.7319, lng: 121.0232 },
  },
  {
    id: "bg042",
    barangay: "Dela Paz Pulot Aplaya",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Dela Paz Pulot Aplaya, Batangas City, Batangas",
    coordinates: { lat: 13.7206, lng: 121.0119 },
  },
  {
    id: "bg043",
    barangay: "Dela Paz Pulot Itaas",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Dela Paz Pulot Itaas, Batangas City, Batangas",
    coordinates: { lat: 13.7093, lng: 121.0006 },
  },
  {
    id: "bg044",
    barangay: "Domoclay",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Domoclay, Batangas City, Batangas",
    coordinates: { lat: 13.698, lng: 120.9893 },
  },
  {
    id: "bg045",
    barangay: "Dumantay",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Dumantay, Batangas City, Batangas",
    coordinates: { lat: 13.6867, lng: 120.978 },
  },
  {
    id: "bg046",
    barangay: "Gulod Itaas",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Gulod Itaas, Batangas City, Batangas",
    coordinates: { lat: 13.6754, lng: 120.9667 },
  },
  {
    id: "bg047",
    barangay: "Gulod Labak",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Gulod Labak, Batangas City, Batangas",
    coordinates: { lat: 13.6641, lng: 120.9554 },
  },
  {
    id: "bg048",
    barangay: "Haligue Kanluran",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Haligue Kanluran, Batangas City, Batangas",
    coordinates: { lat: 13.6528, lng: 120.9441 },
  },
  {
    id: "bg049",
    barangay: "Haligue Silangan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Haligue Silangan, Batangas City, Batangas",
    coordinates: { lat: 13.6415, lng: 120.9328 },
  },
  {
    id: "bg050",
    barangay: "Ilihan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Ilihan, Batangas City, Batangas",
    coordinates: { lat: 13.6302, lng: 120.9215 },
  },
  {
    id: "bg051",
    barangay: "Kumba",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Kumba, Batangas City, Batangas",
    coordinates: { lat: 13.6189, lng: 120.9102 },
  },
  {
    id: "bg052",
    barangay: "Kumintang Ibaba",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Kumintang Ibaba, Batangas City, Batangas",
    coordinates: { lat: 13.7512, lng: 121.0425 },
  },
  {
    id: "bg053",
    barangay: "Kumintang Ilaya",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Kumintang Ilaya, Batangas City, Batangas",
    coordinates: { lat: 13.7625, lng: 121.0538 },
  },
  {
    id: "bg054",
    barangay: "Libjo",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Libjo, Batangas City, Batangas",
    coordinates: { lat: 13.7738, lng: 121.0651 },
  },
  {
    id: "bg055",
    barangay: "Liponpon, Isla Verde",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Liponpon, Isla Verde, Batangas City, Batangas",
    coordinates: { lat: 13.6963, lng: 121.0312 },
  },
  {
    id: "bg056",
    barangay: "Maapas",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Maapas, Batangas City, Batangas",
    coordinates: { lat: 13.7851, lng: 121.0764 },
  },
  {
    id: "bg057",
    barangay: "Mabacong",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Mabacong, Batangas City, Batangas",
    coordinates: { lat: 13.7964, lng: 121.0877 },
  },
  {
    id: "bg058",
    barangay: "Mahabang Dahilig",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Mahabang Dahilig, Batangas City, Batangas",
    coordinates: { lat: 13.8077, lng: 121.099 },
  },
  {
    id: "bg059",
    barangay: "Mahabang Parang",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Mahabang Parang, Batangas City, Batangas",
    coordinates: { lat: 13.819, lng: 121.1103 },
  },
  {
    id: "bg060",
    barangay: "Mahacot Kanluran",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Mahacot Kanluran, Batangas City, Batangas",
    coordinates: { lat: 13.8303, lng: 121.1216 },
  },
  {
    id: "bg061",
    barangay: "Mahacot Silangan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Mahacot Silangan, Batangas City, Batangas",
    coordinates: { lat: 13.8416, lng: 121.1329 },
  },
  {
    id: "bg062",
    barangay: "Malalim",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Malalim, Batangas City, Batangas",
    coordinates: { lat: 13.8529, lng: 121.1442 },
  },
  {
    id: "bg063",
    barangay: "Malibayo",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Malibayo, Batangas City, Batangas",
    coordinates: { lat: 13.7399, lng: 121.0312 },
  },
  {
    id: "bg064",
    barangay: "Malitam",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Malitam, Batangas City, Batangas",
    coordinates: { lat: 13.7286, lng: 121.0199 },
  },
  {
    id: "bg065",
    barangay: "Maruclap",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Maruclap, Batangas City, Batangas",
    coordinates: { lat: 13.7173, lng: 121.0086 },
  },
  {
    id: "bg066",
    barangay: "Pagkilatan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Pagkilatan, Batangas City, Batangas",
    coordinates: { lat: 13.706, lng: 120.9973 },
  },
  {
    id: "bg067",
    barangay: "Paharang Kanluran",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Paharang Kanluran, Batangas City, Batangas",
    coordinates: { lat: 13.6947, lng: 120.986 },
  },
  {
    id: "bg068",
    barangay: "Paharang Silangan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Paharang Silangan, Batangas City, Batangas",
    coordinates: { lat: 13.6834, lng: 120.9747 },
  },
  {
    id: "bg069",
    barangay: "Pallocan Kanluran",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Pallocan Kanluran, Batangas City, Batangas",
    coordinates: { lat: 13.6721, lng: 120.9634 },
  },
  {
    id: "bg070",
    barangay: "Pallocan Silangan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Pallocan Silangan, Batangas City, Batangas",
    coordinates: { lat: 13.6608, lng: 120.9521 },
  },
  {
    id: "bg071",
    barangay: "Pinamucan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Pinamucan, Batangas City, Batangas",
    coordinates: { lat: 13.6495, lng: 120.9408 },
  },
  {
    id: "bg072",
    barangay: "Pinamucan Ibaba",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Pinamucan Ibaba, Batangas City, Batangas",
    coordinates: { lat: 13.6382, lng: 120.9295 },
  },
  {
    id: "bg073",
    barangay: "Pinamucan Silangan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Pinamucan Silangan, Batangas City, Batangas",
    coordinates: { lat: 13.6269, lng: 120.9182 },
  },
  {
    id: "bg074",
    barangay: "Sampaga",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Sampaga, Batangas City, Batangas",
    coordinates: { lat: 13.6156, lng: 120.9069 },
  },
  {
    id: "bg075",
    barangay: "San Agapito, Isla Verde",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "San Agapito, Isla Verde, Batangas City, Batangas",
    coordinates: { lat: 13.685, lng: 121.0199 },
  },
  {
    id: "bg076",
    barangay: "San Agustin Kanluran, Isla Verde",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "San Agustin Kanluran, Isla Verde, Batangas City, Batangas",
    coordinates: { lat: 13.6737, lng: 121.0086 },
  },
  {
    id: "bg077",
    barangay: "San Agustin Silangan, Isla Verde",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "San Agustin Silangan, Isla Verde, Batangas City, Batangas",
    coordinates: { lat: 13.6624, lng: 120.9973 },
  },
  {
    id: "bg078",
    barangay: "San Andres, Isla Verde",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "San Andres, Isla Verde, Batangas City, Batangas",
    coordinates: { lat: 13.6511, lng: 120.986 },
  },
  {
    id: "bg079",
    barangay: "San Antonio, Isla Verde",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "San Antonio, Isla Verde, Batangas City, Batangas",
    coordinates: { lat: 13.6398, lng: 120.9747 },
  },
  {
    id: "bg080",
    barangay: "San Isidro",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "San Isidro, Batangas City, Batangas",
    coordinates: { lat: 13.6285, lng: 120.9634 },
  },
  {
    id: "bg081",
    barangay: "San Jose Sico",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "San Jose Sico, Batangas City, Batangas",
    coordinates: { lat: 13.6172, lng: 120.9521 },
  },
  {
    id: "bg082",
    barangay: "San Miguel",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "San Miguel, Batangas City, Batangas",
    coordinates: { lat: 13.6059, lng: 120.9408 },
  },
  {
    id: "bg083",
    barangay: "San Pedro",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "San Pedro, Batangas City, Batangas",
    coordinates: { lat: 13.7466, lng: 121.0379 },
  },
  {
    id: "bg084",
    barangay: "Santa Clara",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Santa Clara, Batangas City, Batangas",
    coordinates: { lat: 13.7579, lng: 121.0492 },
  },
  {
    id: "bg085",
    barangay: "Santa Rita Aplaya",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Santa Rita Aplaya, Batangas City, Batangas",
    coordinates: { lat: 13.7692, lng: 121.0605 },
  },
  {
    id: "bg086",
    barangay: "Santa Rita Karsada",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Santa Rita Karsada, Batangas City, Batangas",
    coordinates: { lat: 13.7805, lng: 121.0718 },
  },
  {
    id: "bg087",
    barangay: "Santo Domingo",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Santo Domingo, Batangas City, Batangas",
    coordinates: { lat: 13.7918, lng: 121.0831 },
  },
  {
    id: "bg088",
    barangay: "Santo Niño",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Santo Niño, Batangas City, Batangas",
    coordinates: { lat: 13.8031, lng: 121.0944 },
  },
  {
    id: "bg089",
    barangay: "Simlong",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Simlong, Batangas City, Batangas",
    coordinates: { lat: 13.8144, lng: 121.1057 },
  },
  {
    id: "bg090",
    barangay: "Sirang Lupa",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Sirang Lupa, Batangas City, Batangas",
    coordinates: { lat: 13.8257, lng: 121.117 },
  },
  {
    id: "bg091",
    barangay: "Sorosoro Ibaba",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Sorosoro Ibaba, Batangas City, Batangas",
    coordinates: { lat: 13.837, lng: 121.1283 },
  },
  {
    id: "bg092",
    barangay: "Sorosoro Ilaya",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Sorosoro Ilaya, Batangas City, Batangas",
    coordinates: { lat: 13.8483, lng: 121.1396 },
  },
  {
    id: "bg093",
    barangay: "Sorosoro Karsada",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Sorosoro Karsada, Batangas City, Batangas",
    coordinates: { lat: 13.8596, lng: 121.1509 },
  },
  {
    id: "bg094",
    barangay: "Tabangao Ambulong",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Tabangao Ambulong, Batangas City, Batangas",
    coordinates: { lat: 13.7353, lng: 121.0266 },
  },
  {
    id: "bg095",
    barangay: "Tabangao Aplaya",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Tabangao Aplaya, Batangas City, Batangas",
    coordinates: { lat: 13.724, lng: 121.0153 },
  },
  {
    id: "bg096",
    barangay: "Tabangao Dao",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Tabangao Dao, Batangas City, Batangas",
    coordinates: { lat: 13.7127, lng: 121.004 },
  },
  {
    id: "bg097",
    barangay: "Talahib Pandayan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Talahib Pandayan, Batangas City, Batangas",
    coordinates: { lat: 13.7014, lng: 120.9927 },
  },
  {
    id: "bg098",
    barangay: "Talahib Payapa",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Talahib Payapa, Batangas City, Batangas",
    coordinates: { lat: 13.6901, lng: 120.9814 },
  },
  {
    id: "bg099",
    barangay: "Talumpok Kanluran",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Talumpok Kanluran, Batangas City, Batangas",
    coordinates: { lat: 13.6788, lng: 120.9701 },
  },
  {
    id: "bg100",
    barangay: "Talumpok Silangan",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Talumpok Silangan, Batangas City, Batangas",
    coordinates: { lat: 13.6675, lng: 120.9588 },
  },
  {
    id: "bg101",
    barangay: "Tinga Itaas",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Tinga Itaas, Batangas City, Batangas",
    coordinates: { lat: 13.6562, lng: 120.9475 },
  },
  {
    id: "bg102",
    barangay: "Tinga Labak",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Tinga Labak, Batangas City, Batangas",
    coordinates: { lat: 13.6449, lng: 120.9362 },
  },
  {
    id: "bg103",
    barangay: "Tulo",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Tulo, Batangas City, Batangas",
    coordinates: { lat: 13.6336, lng: 120.9249 },
  },
  {
    id: "bg104",
    barangay: "Wawa",
    city: "Batangas City",
    province: "Batangas",
    fullAddress: "Wawa, Batangas City, Batangas",
    coordinates: { lat: 13.6223, lng: 120.9136 },
  },
];

// Helper functions for searching and filtering
export const searchBatangasCityBarangays = (
  query: string
): BatangasCityAddress[] => {
  if (!query || query.length < 2) return [];

  const searchTerm = query.toLowerCase();
  return batangasCityBarangays.filter(
    (address) =>
      address.barangay.toLowerCase().includes(searchTerm) ||
      address.fullAddress.toLowerCase().includes(searchTerm)
  );
};

export const getBarangayByName = (
  barangayName: string
): BatangasCityAddress | undefined => {
  return batangasCityBarangays.find(
    (address) => address.barangay.toLowerCase() === barangayName.toLowerCase()
  );
};

export const getAllBarangayNames = (): string[] => {
  return batangasCityBarangays.map((address) => address.barangay);
};

export const getBarangaysWithCoordinates = (): BatangasCityAddress[] => {
  return batangasCityBarangays.filter((address) => address.coordinates);
};
